import { useState } from "react";

import SearchIcon from "@mui/icons-material/Search";
import FilterAltIcon from "@mui/icons-material/FilterAlt";
import ShareIcon from "@mui/icons-material/Share";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";

import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import EmojiEmotionsOutlinedIcon from "@mui/icons-material/EmojiEmotionsOutlined";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import TableChartIcon from "@mui/icons-material/TableChart";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function StudentLogs() {
  const [showFilter, setShowFilter] = useState(false);
  const [showShare, setShowShare] = useState(false);
  const [activeSort, setActiveSort] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");

  const logs = [
    { query: "Where is Library", time: "10:00 AM", date: "2025-09-02", emotion: "Neutral" },
    { query: "Where's the registrar", time: "10:03 AM", date: "2025-09-17", emotion: "Sad" },
    { query: "Where's the registrar", time: "10:05 AM", date: "2025-09-15", emotion: "Neutral" },
    { query: "Where is Library", time: "10:00 AM", date: "2025-09-20", emotion: "Neutral" },
    { query: "Where is Library", time: "10:03 AM", date: "2025-09-16", emotion: "Happy" },
    { query: "Where's the registrar", time: "10:05 AM", date: "2025-09-19", emotion: "Neutral" },
  ];

  // SEARCH + SORT
  const processedLogs = [...logs]
    .filter((log) => {
      const s = searchTerm.toLowerCase();
      return (
        log.query.toLowerCase().includes(s) ||
        log.date.includes(s) ||
        log.emotion.toLowerCase().includes(s)
      );
    })
    .sort((a, b) => {
      if (activeSort === "date") return new Date(a.date) - new Date(b.date);
      if (activeSort === "emotion") {
        const order = { Neutral: 1, Happy: 2, Sad: 3 };
        return order[a.emotion] - order[b.emotion];
      }
      return 0;
    });

  // PDF EXPORT
  const exportPDF = () => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Student Interaction Logs Report", doc.internal.pageSize.getWidth() / 2, 20, { align: "center" });

    // Metadata
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80);

    const downloadDate = new Date();
    const metadataY = 28;
    doc.text("Generated By: Admin / System", 14, metadataY);
    doc.text(`Download Date: ${downloadDate.toLocaleDateString()} ${downloadDate.toLocaleTimeString()}`, 14, metadataY + 6);

    if (processedLogs.length > 0) {
      const dates = processedLogs.map((log) => new Date(log.date));
      const minDate = new Date(Math.min(...dates));
      const maxDate = new Date(Math.max(...dates));
      doc.text(`Logs Date Range: ${minDate.toLocaleDateString()} – ${maxDate.toLocaleDateString()}`, 14, metadataY + 12);
    }

    // Separator line
    doc.setDrawColor(50);
    doc.setLineWidth(0.5);
    doc.line(14, metadataY + 16, doc.internal.pageSize.getWidth() - 14, metadataY + 16);

    // Table
    const tableData = processedLogs.map((log) => [
      log.query,
      `${log.time} | ${log.date}`,
      log.emotion,
    ]);

    autoTable(doc, {
      startY: metadataY + 22,
      head: [["Query", "Timestamp", "Emotion"]],
      body: tableData,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [60, 60, 60], textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      margin: { left: 14, right: 14 },
    });

    doc.save("student_logs_report.pdf");
    setShowShare(false);
  };

  // CSV EXPORT
  const exportCSV = () => {
    const headers = ["Query", "Time", "Date", "Emotion"];
    const rows = processedLogs.map((log) => [log.query, log.time, log.date, log.emotion]);

    const downloadDate = new Date();
    const reportInfo = [
      ["Student Interaction Logs Report"],
      ["Generated By: Admin / System"],
      [`Download Date: ${downloadDate.toLocaleDateString()} ${downloadDate.toLocaleTimeString()}`],
    ];

    if (processedLogs.length > 0) {
      const dates = processedLogs.map((log) => new Date(log.date));
      const minDate = new Date(Math.min(...dates));
      const maxDate = new Date(Math.max(...dates));
      reportInfo.push([`Logs Date Range: ${minDate.toLocaleDateString()} – ${maxDate.toLocaleDateString()}`]);
    }

    reportInfo.push([""]); // blank line before table

    const csvContent = [
      ...reportInfo.map((r) => r.join(",")),
      headers.join(","),
      ...rows.map((r) => r.join(",")),
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "student_logs_report.csv";
    link.click();

    setShowShare(false);
  };

  return (
    <div className="page">
      <h1>Student Logs</h1>

      <div className="logsHeaderInfo">
        <p className="logsDescription">
          View and monitor student interactions and activity records.
        </p>
        <div className="logsDivider"></div>
      </div>

      {/* TOOLBAR */}
      <div className="logsToolbar">
        <div className="logsToolbarLeft">
          {/* SEARCH */}
          <div className="searchWrapper">
            <input
              type="text"
              className="logsSearch"
              placeholder="Search Here"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
            <SearchIcon className="searchIcon" />
          </div>

          {/* FILTER */}
          <div className="dropdownWrapper">
            <button
              className="filterBtn"
              onClick={() => {
                setShowFilter(!showFilter);
                setShowShare(false);
              }}
            >
              <FilterAltIcon className="filterIcon" />
              <span className="btnText">FILTER</span>
              <ArrowDropDownIcon className="dropdownIcon" />
            </button>

            {showFilter && (
              <div className="dropdownMenu">
                <div
                  className={`dropdownItem ${activeSort === "date" ? "active" : ""}`}
                  onClick={() => {
                    setActiveSort("date");
                    setShowFilter(false);
                  }}
                >
                  <CalendarMonthIcon />
                  Date
                </div>

                <div
                  className={`dropdownItem ${activeSort === "emotion" ? "active" : ""}`}
                  onClick={() => {
                    setActiveSort("emotion");
                    setShowFilter(false);
                  }}
                >
                  <EmojiEmotionsOutlinedIcon />
                  Emotion
                </div>
              </div>
            )}
          </div>
        </div>

        {/* SHARE */}
        <div className="dropdownWrapper" style={{ marginLeft: "auto" }}>
          <button
            className="shareBtn"
            onClick={() => {
              setShowShare(!showShare);
              setShowFilter(false);
            }}
          >
            <ShareIcon className="shareIcon" />
            <span className="btnText">Share</span>
            <ArrowDropDownIcon className="dropdownIcon" />
          </button>

          {showShare && (
            <div className="dropdownMenu">
              <div className="dropdownItem" onClick={exportPDF}>
                <PictureAsPdfIcon />
                PDF
              </div>
              <div className="dropdownItem" onClick={exportCSV}>
                <TableChartIcon />
                CSV
              </div>
            </div>
          )}
        </div>
      </div>

      {/* TABLE */}
      <div className="logsTableContainer">
        <div className="logsTableHeader">
          <div>Query</div>
          <div>Timestamp</div>
          <div>Emotion</div>
          <div>Actions</div>
        </div>

        {processedLogs.map((log, index) => (
          <div className="logsTableRow" key={index}>
            <div className="logsQuery">"{log.query}"</div>
            <div className="logsTimestamp">
              <span>{log.time}</span>
              <span className="logsDate">{log.date}</span>
            </div>
            <div className={`logsEmotion ${log.emotion.toLowerCase()}`}>
              {log.emotion}
            </div>
            <div className="logsAction">Answer</div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default StudentLogs;
